#!/usr/bin/env bash

# Interactive configuration and generated-script helpers.

GENERATED_DIR="${SCRIPT_DIR}/generated"

interactive_require_whiptail() {
  if ! command_exists whiptail; then
    fatal "The interactive command requires 'whiptail'. Install it with: apt install whiptail"
  fi
}

interactive_get_hostname() {
  local ctid="${1:-}"
  local default_hostname=""

  if [[ -n "${ctid}" ]] && lxc_exists "${ctid}"; then
    default_hostname="$(
      pct config "${ctid}" 2>/dev/null |
        awk '/^hostname: / {print $2; exit}'
    )"
  fi

  [[ -n "${default_hostname}" ]] || default_hostname="lxc-${ctid}"

  whiptail \
    --inputbox \
    "Hostname:" \
    10 60 \
    "${default_hostname}" \
    3>&1 1>&2 2>&3
}

interactive_select_profile() {
  local profiles=()
  local profile
  local selected

  while IFS= read -r profile; do
    [[ -n "${profile}" ]] || continue
    profiles+=("${profile}" "")
  done < <(
    find "${PROFILE_DIR}" \
      -maxdepth 1 \
      -type f \
      -name '*.conf' \
      -printf '%f\n' |
      sed 's/\.conf$//' |
      sort
  )

  if [[ ${#profiles[@]} -eq 0 ]]; then
    fatal "No configuration profiles are available."
  fi

  selected="$(
    whiptail \
      --title "Configuration Profile" \
      --menu "Select a profile:" \
      20 70 10 \
      "${profiles[@]}" \
      3>&1 1>&2 2>&3
  )" || return 1

  printf '%s\n' "${selected}"
}

interactive_select_modules() {
  local modules=()
  local module
  local selected

  while IFS= read -r module; do
    [[ -n "${module}" ]] || continue
    modules+=("${module}" "" "OFF")
  done < <(list_modules | sort)

  if [[ ${#modules[@]} -eq 0 ]]; then
    fatal "No provisioning modules are available."
  fi

  selected="$(
    whiptail \
      --title "Provisioning Modules" \
      --checklist \
      "Select modules to include:" \
      20 70 10 \
      "${modules[@]}" \
      3>&1 1>&2 2>&3
  )" || return 1

  printf '%s\n' "${selected}" |
    tr ' ' '\n' |
    sed 's/^"//; s/"$//'
}

interactive_get_script_name() {
  local default_name="${1:-configuration}"

  whiptail \
    --inputbox \
    "Name for the generated configuration script:" \
    10 60 \
    "${default_name}" \
    3>&1 1>&2 2>&3
}

interactive_validate_script_name() {
  local name="${1:-}"

  [[ -n "${name}" ]] ||
    fatal "Generated script name cannot be empty."

  [[ "${name}" =~ ^[a-zA-Z0-9._-]+$ ]] ||
    fatal "Invalid generated script name '${name}'. Use only letters, numbers, '.', '_' and '-'."
}

interactive_generate_script() {
  local ctid="${1:-}"
  local hostname="${2:-}"
  local profile="${3:-}"
  local script_name="${4:-}"
  shift 4 || true

  local modules=("$@")
  local module
  local script_file

  interactive_validate_script_name "${script_name}"

  mkdir -p "${GENERATED_DIR}"

  script_file="${GENERATED_DIR}/${script_name}.sh"

  if [[ -e "${script_file}" ]]; then
    if ! whiptail \
      --title "File Already Exists" \
      --yesno \
      "The following file already exists:\n\n${script_file}\n\nOverwrite it?" \
      12 70 \
      3>&1 1>&2 2>&3
    then
      return 1
    fi
  fi

  # shellcheck disable=SC2016  # These printf lines emit literal shell syntax into the generated script; it must not expand here.
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' ''
    printf '%s\n' '# Generated by lxc-configurator.'
    printf '%s\n' "# Configurator version: ${CONFIGURATOR_VERSION}"
    printf '%s\n' "# Recipe format: ${RECIPE_FORMAT_VERSION}"
    printf '%s\n' "# Generated: $(date --iso-8601=seconds)"
    printf '%s\n' ''
    printf '%s\n' 'set -Eeuo pipefail'
    printf '%s\n' ''
    printf '%s\n' 'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"'
    printf '%s\n' 'CONFIGURATOR_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"'
    printf '%s\n' ''
    printf '%s\n' 'cd "${CONFIGURATOR_DIR}"'
    printf '%s\n' ''
    printf '%s\n' '# Usage:'
    printf '%s\n' "#   ./generated/${script_name}.sh [CTID] [HOSTNAME]"
    printf '%s\n' ''
    printf '%s\n' '# Default values captured during generation.'
    printf '%s\n' "DEFAULT_CTID=\"${ctid}\""
    printf '%s\n' "DEFAULT_HOSTNAME=\"${hostname}\""
    printf '%s\n' ''
    printf '%s\n' 'CTID="${1:-${DEFAULT_CTID}}"'
    printf '%s\n' 'HOSTNAME="${2:-${DEFAULT_HOSTNAME}}"'
    printf '%s\n' ''
    printf '%s\n' 'export CTID'
    printf '%s\n' 'export HOSTNAME'
    printf '%s\n' ''
    printf '%s\n' 'echo "Configuring LXC ${CTID} (${HOSTNAME})..."'
    printf '%s\n' ''

    if [[ -n "${profile}" ]]; then
      printf '%s\n' "# Profile: ${profile}"
      printf '%s\n' './configurator.sh configure "${CTID}" "'"${profile}"'"'
    else
      printf '%s\n' '# Custom module selection'

      for module in "${modules[@]}"; do
        [[ -n "${module}" ]] || continue

        printf '%s\n' \
          "./configurator.sh module \"${module}\" \"\${CTID}\""
      done
    fi

    printf '%s\n' ''
    printf '%s\n' 'echo "Configuration completed."'
  } > "${script_file}"

  chmod +x "${script_file}"

  printf '%s\n' "${script_file}"
}

interactive_print_cli_command() {
  local ctid="${1:-}"
  local hostname="${2:-}"
  local profile="${3:-}"
  shift 3 || true

  local modules=("$@")
  local module

  echo
  log_info "Equivalent CLI commands:"

  if [[ -n "${profile}" ]]; then
    printf './configurator.sh configure %q %q\n' \
      "${ctid}" \
      "${profile}"
  else
    for module in "${modules[@]}"; do
      [[ -n "${module}" ]] || continue

      printf './configurator.sh module %q %q\n' \
        "${module}" \
        "${ctid}"
    done
  fi

  echo
  log_info "Selected hostname: ${hostname}"
}

run_interactive() {
  local ctid="${1:-}"
  local generate_cli_command=false

  shift || true

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --generate-cli-command)
        generate_cli_command=true
        shift
        ;;

      *)
        fatal "Unknown interactive option: $1"
        ;;
    esac
  done

  [[ -n "${ctid}" ]] ||
    fatal "Usage: ./configurator.sh interactive <ctid> [--generate-cli-command]"

  if ! lxc_exists "${ctid}"; then
    fatal "LXC ${ctid} does not exist."
  fi

  interactive_require_whiptail

  local hostname
  local mode
  local profile=""
  local modules=()
  local script_name
  local script_file

  hostname="$(interactive_get_hostname "${ctid}")" || {
    log_info "Interactive configuration cancelled."
    return 0
  }

  mode="$(
    whiptail \
      --title "Configuration Mode" \
      --menu \
      "How should this LXC be configured?" \
      15 70 5 \
      "profile" "Use an existing configuration profile" \
      "custom" "Select individual provisioning modules" \
      3>&1 1>&2 2>&3
  )" || {
    log_info "Interactive configuration cancelled."
    return 0
  }

  case "${mode}" in
    profile)
      profile="$(interactive_select_profile)" || {
        log_info "Interactive configuration cancelled."
        return 0
      }
      ;;

    custom)
      mapfile -t modules < <(interactive_select_modules)

      if [[ ${#modules[@]} -eq 0 ]]; then
        log_warn "No modules selected."
        return 1
      fi
      ;;

    *)
      fatal "Unknown interactive configuration mode: ${mode}"
      ;;
  esac

  if [[ "${generate_cli_command}" == "true" ]]; then
    if [[ "${mode}" == "profile" ]]; then
      interactive_print_cli_command \
        "${ctid}" \
        "${hostname}" \
        "${profile}"
    else
      interactive_print_cli_command \
        "${ctid}" \
        "${hostname}" \
        "" \
        "${modules[@]}"
    fi

    return 0
  fi

  script_name="$(
    interactive_get_script_name \
      "${profile:-configuration}"
  )" || {
    log_info "Interactive configuration cancelled."
    return 0
  }

  interactive_validate_script_name "${script_name}"

  if [[ "${mode}" == "profile" ]]; then
    script_file="$(
      interactive_generate_script \
        "${ctid}" \
        "${hostname}" \
        "${profile}" \
        "${script_name}"
    )" || {
      log_info "Interactive configuration cancelled."
      return 0
    }
  else
    script_file="$(
      interactive_generate_script \
        "${ctid}" \
        "${hostname}" \
        "" \
        "${script_name}" \
        "${modules[@]}"
    )" || {
      log_info "Interactive configuration cancelled."
      return 0
    }
  fi

  log_success "Generated configuration script:"
  log_info "${script_file}"

  echo

  whiptail \
    --title "Configuration Script" \
    --msgbox \
    "Generated:\n\n${script_file}\n\nThe script was not executed." \
    12 70

  echo
}
