#!/usr/bin/env bash

# Generated recipe creation and execution.

GENERATED_DIR="${SCRIPT_DIR}/generated"

recipe_require_whiptail() {
  if ! command_exists whiptail; then
    fatal "The interactive mode requires 'whiptail'. Install it with: apt install whiptail"
  fi
}

recipe_list_profiles() {
  find "${PROFILE_DIR}" \
    -maxdepth 1 \
    -type f \
    -name '*.conf' \
    -printf '%f\n' |
    sed 's/\.conf$//' |
    sort
}

recipe_list_modules() {
  list_modules
}

recipe_next_filename() {
  local name="${1:-recipe}"
  local candidate="${GENERATED_DIR}/${name}.sh"
  local index=2

  while [[ -e "${candidate}" ]]; do
    candidate="${GENERATED_DIR}/${name}-${index}.sh"
    ((index++))
  done

  printf '%s\n' "${candidate}"
}

recipe_generate() {
  local name="${1:-recipe}"
  local mode="${2:-profile}"
  local profile="${3:-}"
  shift 3 || true

  local ctid="${RECIPE_CTID:-250}"
  local hostname="${RECIPE_HOSTNAME:-}"
  local ip="${RECIPE_IP:-auto}"
  local gateway="${RECIPE_GATEWAY:-}"
  local start="${RECIPE_START:-0}"

  local output_file
  output_file="$(recipe_next_filename "${name}")"

  mkdir -p "${GENERATED_DIR}"

  {
    cat <<EOF
#!/usr/bin/env bash

# Generated by lxc-configurator ${CONFIGURATOR_VERSION}
# Generated recipe: ${name}
#
# This file is a reusable configuration recipe.
#
# Default overrides:
#   CTID=${ctid}
#   HOSTNAME=${hostname:-<generated>}
#   IP=${ip}
#
# Example:
#   ./configurator.sh run generated/${name}.sh
#
# Override values:
#   CTID=251 HOSTNAME=my-server ./configurator.sh run generated/${name}.sh

RECIPE_VERSION="${CONFIGURATOR_VERSION}"

CONFIGURATOR_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
CONFIGURATOR="\${CONFIGURATOR_DIR}/configurator.sh"

CTID="\${CTID:-${ctid}}"
HOSTNAME="\${HOSTNAME:-${hostname}}"
IP="\${IP:-${ip}}"
GATEWAY="\${GATEWAY:-${gateway}}"

if [[ -z "\${CTID}" ]]; then
  echo "CTID is required." >&2
  exit 1
fi

EOF

    if [[ "${mode}" == "profile" ]]; then
      cat <<EOF
"\${CONFIGURATOR}" configure "\${CTID}" "${profile}"

EOF
    else
      if [[ -n "${hostname}" || -n "${ip}" ]]; then
        cat <<'EOF'
# Custom configuration values are available above for commands
# generated below.

EOF
      fi

      local module
      # shellcheck disable=SC2016  # Literal ${VAR} text is intentional: it's written into the generated recipe script, not expanded now.
      for module in "$@"; do
        case "${module}" in
          create)
            local create_args=()

            if [[ -n "${HOSTNAME}" ]]; then
              create_args+=(--hostname '"${HOSTNAME}"')
            fi

            if [[ -n "${IP}" ]]; then
              create_args+=(--ip '"${IP}"')
            fi

            if [[ -n "${GATEWAY}" ]]; then
              create_args+=(--gateway '"${GATEWAY}"')
            fi

            if [[ "${start}" == "1" ]]; then
              create_args+=(--start)
            else
              create_args+=(--no-start)
            fi

            printf '"${CONFIGURATOR}" create "\${CTID}"'
            printf ' %s' "${create_args[@]}"
            printf '\n\n'
            ;;

          *)
            printf '"${CONFIGURATOR}" module "%s" "\${CTID}"\n\n' "${module}"
            ;;
        esac
      done
    fi

    cat <<'EOF'
echo
echo "[OK] Recipe completed."
EOF
  } > "${output_file}"

  chmod 755 "${output_file}"

  log_success "Generated recipe: ${output_file}" >&2
  printf '%s\n' "${output_file}"
}

recipe_check_version() {
  local recipe_file="${1:-}"

  [[ -f "${recipe_file}" ]] || return 1

  local recipe_version
  recipe_version="$(
    sed -nE \
      's/^RECIPE_VERSION="([^"]+)".*/\1/p' \
      "${recipe_file}" |
      head -n1
  )"

  if [[ -z "${recipe_version}" ]]; then
    log_warn "Recipe does not contain a configurator version."
    return 0
  fi

  if [[ "${recipe_version}" != "${CONFIGURATOR_VERSION}" ]]; then
    log_warn \
      "Recipe was generated by lxc-configurator ${recipe_version}, " \
      "but current version is ${CONFIGURATOR_VERSION}."
    log_warn "The recipe may need to be regenerated."
  fi
}

run_recipe() {
  local recipe_file="${1:-}"
  shift || true

  if [[ -z "${recipe_file}" ]]; then
    fatal "Usage: ./configurator.sh run <recipe> [arguments]"
  fi

  if [[ ! -f "${recipe_file}" ]]; then
    if [[ -f "${GENERATED_DIR}/${recipe_file}" ]]; then
      recipe_file="${GENERATED_DIR}/${recipe_file}"
    elif [[ -f "${GENERATED_DIR}/${recipe_file}.sh" ]]; then
      recipe_file="${GENERATED_DIR}/${recipe_file}.sh"
    else
      fatal "Recipe not found: ${recipe_file}"
    fi
  fi

  recipe_check_version "${recipe_file}"

  log_info "Running recipe '${recipe_file}'..."

  (
    cd "${SCRIPT_DIR}" || exit

    if [[ $# -gt 0 ]]; then
      "$recipe_file" "$@"
    else
      "$recipe_file"
    fi
  )
}
